"""
Django settings for server project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv
from api.deployment import required_environment

load_dotenv()


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

APP_ENV = os.environ.get("APP_ENV", "DEVELOPMENT").upper()
IS_PRODUCTION = APP_ENV == "PRODUCTION"
FRONTEND_URL = (
    required_environment("FRONTEND_URL")
    if IS_PRODUCTION
    else os.environ.get("FRONTEND_URL", "http://localhost:3000")
)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = required_environment("API_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = APP_ENV == "DEVELOPMENT"

ALLOWED_HOSTS = (
    required_environment("API_ALLOWED_HOSTS").split()
    if IS_PRODUCTION
    else os.environ.get("API_ALLOWED_HOSTS", ".localhost 127.0.0.1 [::1]").split()
)

# Application definition

INSTALLED_APPS = [
    "unfold",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "colorfield",
    "django_extensions",
    "rest_framework",
    "corsheaders",
    "api.healthcheck",
    "agronomy_club"
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://localhost:3003",
    "http://127.0.0.1:3000",
    FRONTEND_URL
] if not IS_PRODUCTION else [FRONTEND_URL]

CSRF_TRUSTED_ORIGINS = [FRONTEND_URL]

if IS_PRODUCTION:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = False
    SECURE_HSTS_PRELOAD = False

ROOT_URLCONF = "api.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

UNFOLD = {
    "COLORS": {
        "base": {
            "50": "#fcfbf7",
            "100": "#fcfbf7",
            "200": "#d7e2d4",
            "300": "#3F7D27",
            "600": "#3F7D27",
        },
        "primary": {
            "50": "#fcfbf7",
            "100": "#fcfbf7",
            "200": "#d7e2d4",
            "300": "#3F7D27",
            "400": "#3F7D27",
            "500": "#166534",
            "600": "#166534",
            "700": "#166534",
        },
        "font": {
            "subtle-light": "#d7e2d4",  # text-base-500
            "subtle-dark": "#d7e2d4",  # text-base-400
            "default-light": "#3F7D27",  # text-base-600
            "default-dark": "#fcfbf7",  # text-base-300
            "light-important": "#166534",  # text-base-700
            "dark-important": "#166534",  # text-base-200
        }
    }
}

WSGI_APPLICATION = "api.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": (
            required_environment("POSTGRES_NAME")
            if IS_PRODUCTION
            else os.environ.get("POSTGRES_NAME", "postgres")
        ),
        "USER": (
            required_environment("POSTGRES_USER")
            if IS_PRODUCTION
            else os.environ.get("POSTGRES_USER", "postgres")
        ),
        "PASSWORD": (
            required_environment("POSTGRES_PASSWORD")
            if IS_PRODUCTION
            else os.environ.get("POSTGRES_PASSWORD", "password")
        ),
        "HOST": (
            required_environment("POSTGRES_HOST")
            if IS_PRODUCTION
            else os.environ.get("POSTGRES_HOST", "host.docker.internal")
        ),
        "PORT": os.environ.get("POSTGRES_PORT", "5432"),
        "CONN_MAX_AGE": 60 if IS_PRODUCTION else 0,
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-au"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

PROJECT_ROOT = os.path.dirname(os.path.dirname(
    os.path.dirname(os.path.abspath(__file__))))  # <- '/' directory

STATIC_URL = "/static/"

# STATIC_ROOT is where the static files get copied to when "collectstatic" is run.
STATIC_ROOT = BASE_DIR / "static_files"

# This is where to _find_ static files when 'collectstatic' is run.
# These files are then copied to the STATIC_ROOT location.
STATICFILES_DIRS = [BASE_DIR / "static"]

# The directory to store images and other media
MEDIA_ROOT = BASE_DIR/"media"

# The path to serve images and other media
MEDIA_URL = "/media/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
