# Generated by Django 5.2.16 on 2026-09-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agronomy_club', '0017_resource_public_alter_quiz_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='firebase_uid',
            field=models.CharField(blank=True, editable=False, max_length=128, null=True, unique=True),
        ),
    ]
