# Generated by Django 5.1.15 on 2026-09-19 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agronomy_club', '0018_user_firebase_uid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Member', 'verbose_name_plural': 'Members'},
        ),
    ]
